apiVersion: v1
kind: Service
metadata:
  name: exchange-meeting-room-exporter
  labels:
    app: exchange-meeting-room-exporter
spec:
  type: NodePort
  ports:
  - port: 8000
    name: http
    protocol: TCP
  selector:
    app: exchange-meeting-room-exporter
